toggl/mobileapp

Toggl.Foundation.Tests/Helpers/ApiExceptions.cs, Toggl.Foundation.Tests/Sync/States/Push/BaseStates/BaseCreateEntityStateTests.cs, Toggl.Foundation.Tests/Sync/States/Push/BaseStates/BaseDeleteEntityStateTests.cs, Toggl.Foundation.Tests/Sync/States/Push/BaseStates/BasePushEntityStateTests.cs, Toggl.Foundation.Tests/Sync/States/Push/BaseStates/BaseUpdateEntityStateTests.cs
Some tests were incorrectly used and weren't discovered and run by XUnit. This fixes it.
Squash whenever
=> Fix BasePushEntityStateTests

Toggl.Daneel/ViewControllers/MainViewController.cs, Toggl.Daneel/ViewControllers/SelectProjectViewController.cs, Toggl.Daneel/ViewControllers/StartTimeEntryViewController.cs, Toggl.Daneel/ViewSources/GroupedCollectionTableViewSource.cs, Toggl.Daneel/ViewSources/MainTableViewSource.cs, Toggl.Daneel/ViewSources/SelectProjectTableViewSource.cs, Toggl.Daneel/ViewSources/StartTimeEntryTableViewSource.cs, Toggl.Daneel/ViewSources/TimeEntriesLogViewSource.cs, Toggl.Foundation.MvvmCross/Collections/NestableObservableCollection.cs, Toggl.Foundation.MvvmCross/ViewModels/SelectProjectViewModel.cs, Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
Closes #1523, closes #1784
The main idea behind this PR is that the `GroupedCollectionTableViewSource` handles its own internal state (`ItemsSource`) and makes sure that the displayed sections and rows in the `UITableView` always match the state of the `ItemsSource`. This means that it is not possible to bind anything directly to the `ItemsSource` (as we normally do), but we must rather bind the collection from the VM to the `ObservableCollection` property.
Whenever the `ObservableCollection` changes, the `CollectionChanged` or `OnChildCollectionChanged` events are invoked. We know exactly how the collection was changed (add/delete/replace/...) and we can update both the internal collection and the `UITableView` state - it is important to do this in between `TableView.BeginUpdate()` and …
=> Fix the :bug: - once and for all

Toggl.Daneel/Binding/DatePickerDateTimeOffsetTargetBinding.cs, Toggl.Foundation.MvvmCross/ViewModels/EditDurationViewModel.cs
Closes #1887 
This fixes the glitch for sure, but I'm not 100% sure we're on the correct path here, since the problem happens only when tapping the end time and I would expect the same issue with start time too.
=> Fix picker issue when editing end time

Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs, Toggl.Foundation.Tests/MvvmCross/ViewModels/StartTimeEntryViewModelTests.cs
This is not directly addressing any issue, but it takes care of a potentially ugly bug.
The thing is that `Prepare(StartTimeEntryParameters parameter)` was being called twice in `StartTimeEntryViewModel`, which caused the observable sequence to execute twice. This is due to the use of `Init`, which is needed for 3D Touch to work.
My solution is to use the method `Prepare` (without params) along with `Init`. `Init` is called only for 3D Touch, and `Prepare()` is called always. According to the [docs](https://www.mvvmcross.com/documentation/fundamentals/navigation) `Prepare()` is where parameter agnostic stuff should be initialized.
Please review and test thoroughly, I have no idea what I'm doing.
=> :construction: Refactor StartTimeEntryViewModel initialization

Toggl.Daneel/ViewControllers/Settings/SettingsViewController.xib
Closes #2033
All carets are now properly spaced:
Compared to the rest of the app:
=> Fix misaligned carets in the settings view

.gitignore
Rider keeps generating these folders.
🦑 whenever
=> Add *Undefined*Tools Rider's generated files to gitignore

Toggl.Daneel/ViewControllers/EditDurationViewController.cs
Closes #1434, maybe related to #1436
Making the `DurationInput` first responder of the View Controller.  
I was wondering whether we should not replace the current duration with `00:00` since now the keyboard opens automatically. (See the attached GIF)
Thoughts would be appreciated.
=> show keyboard when edit view appears

Toggl.Giskard/Services/GoogleService.cs
In theory, this solves the Google login issue reported by @pe0ny, but I couldn't confirm that so far because I wasn't able to reproduce the issue in the first place.
=> Fix automatic login with Google

Toggl.Giskard/Activities/StartTimeEntryActivity.cs
Closes #2619 
Marshalling wasn’t enough, so I’m adding a small throttle; long enough to allow continuing typing yet small enough to feel instant once the user stops typing.
Functional testing in a real device (preferably a low-end one) is mandatory.
Squash whenever
=> Fix perceived sluggishness when starting a time entry

Toggl.Foundation.MvvmCross/FoundationExtensions.cs, Toggl.Foundation.MvvmCross/MvvmCrossFoundation.cs
It fixes the injection of the ISchedulerProvider that is crashing giskard at runtime.
Introduced by #2850 
Closes Nothing
We need to keep the app running.
It just uses the `Mvx.RegisterSingleton` that was missing.
I don't know of any other ways. Improvements are always welcome.
Please check that develop breaks for giskard and daneel and it doesn't after the change.
Anyone, after testing on both platforms.
=> Fix missing ISchedulerProvider injection

Toggl.Foundation.MvvmCross/ViewModels/RatingViewModel.cs, Toggl.Foundation.Tests/MvvmCross/ViewModels/RatingViewModelTests.cs, Toggl.Foundation/Analytics/BaseAnalyticsService.cs, Toggl.Foundation/Analytics/IAnalyticsService.cs
This adds more rating view events. This was already done in 1.8.2 and released to users, so we better have the same change here too!
Cherry pick of #2987
Because this was released with 1.8.2, while 1.9 was branched from 1.8.1 and we don't want to lose the events until 1.10 again.
git fu
Make sure I didn't do git poo.
Whoever is handling 1.9.
=> Add more rating view events

Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs, Toggl.Giskard/Activities/SettingsActivity.ViewBinds.cs, Toggl.Giskard/Activities/SettingsActivity.cs, Toggl.Giskard/Resources/layout/SettingsActivity.axml, Toggl.Giskard/Resources/values/Strings.xml, Toggl.PrimeRadiant/Settings/IUserPreferences.cs, Toggl.PrimeRadiant/Settings/SettingsStorage.cs
We're adding the running timer/stopped timer notifications from the old app. This is the first step, where we add the settings checkboxes for them.
Closes #3054
So the users can turn them on and off.
By adding the appropriate fields to the `SettingsStorage` in `PrimeRadiant`
This is the simplest way tbh.
None that I've noticed.
Go to settings, click the switches around; close the app, open it — they should be there; log out — the settings should be forgotten.
All yours!
=> Add idle/running notification settings

Toggl.Daneel/Startup/AppDelegate.cs
There are 2 ways to invoke a siri intent, by speaking to Siri, and by tapping the Shortcut, this PR will handle the case
when user taps it
Closes #3153
Cover all the cases
By open the "stop deeplink" when manually invoking intent
This is probably the easiest way.
Not that I know of.
- Start a time entry
- Invoke the stop shortcut by tapping on it
Anyone
=> ⏰ handle stop timer intent when user invoke by tapping

Toggl.Giskard/Extensions/ActivityExtensions.cs
Fixes the Oreo problems with notification emitting the sound.
Please take a look at the issue to properly understand this solution.
Closes #3275 
Cause the sounds are annoying for these notifications.
Read the issue to understand.
Because Google thinks it's better to work on a new Pixel phone than fix their own bugs.
Zilch.
Read the issue!!!
Yeah, whatever.
=> Prevent notification sounds in Oreo/Pie

Toggl.Giskard/Resources/layout/AboutActivity.axml, Toggl.Giskard/Resources/layout/MainActivity.axml, Toggl.Giskard/Resources/layout/ReportsActivity.axml, Toggl.Giskard/Resources/layout/SettingsActivity.axml, Toggl.Giskard/Resources/layout/TokenResetActivity.axml, Toggl.Giskard/Resources/values/Styles.xml
This is an improvement to reduce overdraw on the main log, but also every other activity that had the background color set to `@color/lightGray`.
Closes #3412 
We were overdrawing quite a lot in the main log. This simple change reduces that, slightly improving the general performance of the MainActivity (gotta measure that).
The window background colour is set the colour of the root container in the activity, removing the need to re-set the background colour when inflating the view.
I don't know any other way.
There's more to do about the overdraw in the main log, but it will require more work and thought. So I'll add another PR just for that.
All other activities using the AppTheme were affected, so I've removed the background there as well, reducing overdraw in the other activities. …
=> Sanic boosters: Remove easy overdraw

Toggl.Foundation/Properties/AssemblyInfo.cs, Toggl.Tools/SyncDiagramGenerator/DotFileWriter.cs, Toggl.Tools/SyncDiagramGenerator/Node.cs, Toggl.Tools/SyncDiagramGenerator/SubGraph.cs, Toggl.Tools/SyncDiagramGenerator/SyncDiagramGenerator.cs
When I say prettier, I mean: easier to use.
I:
- 🔲grouped the subgraphs that deal with specific entities
- 🌈colour coded retry related code
- ↔️trimming of interface prefixes like `IThradSafe`
- [some general Graphviz settings that improve layout](https://github.com/toggl/mobileapp/pull/3721/files#diff-f0e9824227055edb7ab16cb60625ac49R181)
Here is an excerpt of what it looks like now:
Will look even better once #3717 is merged.
So we can easier see if something is wrong with the graph, use it to teach people about syncing easier, and generally decrease the difficulty of wrapping ones head around it.
Hardcoding of some special cases, through type and string matching. It'll be easy enough to change if we make significant changes to our syncing algo though.
For the grouping specifically, I …
=> Make sync graph prettier

Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs, Toggl.Daneel/ViewSources/CalendarCollectionViewSource.cs, Toggl.Daneel/Views/Calendar/CalendarCollectionViewLayout.cs, Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs
The calendar view wasn't observing the timezone correctly. This introduces a fix for that and removes an unneeded observable.
Closes #3722 
🚫 🐛 
`.ToLocalTime()` was needed to observe the timezone correctly. I took the opportunity to 🔥 a confusing (and unneeded) observable and make everything depend on `ITimeService`.
None.
Please give it a try in different timezones and make sure what you see in the calendar view is what you expect 😄 
⛔️ Only me.
=> Fix calendar view not observing timezone

Toggl.Giskard.Tests.UI/AndroidAccessibilityNames.cs
This fixes the current giskard ui tests for the login screen
Closes #4039 
The accessibility names were wrong, that's it.
🦑 it, asap
=> Fix giskard login UI tests

Toggl.Giskard/Toggl.Giskard.csproj, Toggl.Giskard/Views/EditDuration/Shapes/ClockDial.cs, Toggl.Giskard/Views/EditDuration/WheelBackgroundView.cs
This is PR adds the part of the wheel component that draws the background of the wheel that is basically static. The background is composed of the grey arc and the numbers that represent the dial on the wheel.
Closes #4145
Part of #4147 
It's part of the wheel, it would be weird without it.
I've added another view for the background wheel that is basically composed of a full wheel and clock dial. That's it, the logic is very similar to the ForegroundWheel, except there's no user interaction with this view.
This was very easy to do. Feel free to suggest something else.
None.
You can see the view if you put it in some layout inside the app. You have to specify the width and height of the view. Anything like:
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout …
```
=> Droid background wheel: background wheel and inner clock

Toggl.Daneel/Extensions/Reactive/UISwitchExtensions.cs, Toggl.Daneel/ViewControllers/Settings/SettingsViewController.cs, Toggl.Daneel/ViewControllers/Settings/SettingsViewController.designer.cs, Toggl.Daneel/ViewControllers/Settings/SettingsViewController.xib, Toggl.Foundation.MvvmCross/ViewModels/Settings/SettingsViewModel.cs, Toggl.Foundation.Tests/MvvmCross/ViewModels/SettingsViewModelTests.cs, Toggl.Foundation/Resources.Designer.cs, Toggl.Foundation/Resources.resx, Toggl.Giskard/Activities/SettingsActivity.ViewBinds.cs, Toggl.Giskard/Activities/SettingsActivity.cs, Toggl.Giskard/Resources/layout/SettingsActivity.axml, Toggl.Giskard/Resources/values/Strings.xml
Adds `group similar time entries` to Settings screen.
Closes #4217 
Users want customization. Also, 🎡wheels.
The usuals.
Read previous point. Consistency.
None noticed.
I have zero ideas why xcode messed up the `.designer.cs` file. I believe it's fine.
Commit by commit makes most sense:
* Foundation
* iOS
* Android
* Test
Me and this guy @simonrozsival.
=> Add Group TEs setting into the settings screen

Toggl.Foundation.MvvmCross/ViewModels/Calendar/CalendarViewModel.cs, Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs, Toggl.Foundation.MvvmCross/ViewModels/MainViewModel.cs, Toggl.Foundation.Tests/MvvmCross/ViewModels/CalendarViewModelTests.cs, Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
Changes the parameter of the `EditTimeEntryViewModel` so that it supports `long[]`.
Part of #4219 
So that we can send groups as well as TEs to the EditView.
By arraying.
Who knows.
Side effect is that I've fixed some dubbious tests related to the thing along the way.
Careful examination of code transformation. 👅 
🔟 People
=> Change parameters type for EditTimeEntryViewModel

Toggl.Foundation.MvvmCross/Interfaces/IDiffableByIdentifier.cs, Toggl.Foundation.MvvmCross/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarBaseQuickSelectShortcut.cs, Toggl.Foundation.MvvmCross/ViewModels/ReportsCalendar/ReportsCalendarDayViewModel.cs, Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableBeginningOfWeekViewModel.cs, Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableClientViewModel.cs, Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableColorViewModel.cs, Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableCountryViewModel.cs, Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableDateFormatViewModel.cs, Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableDurationFormatViewModel.cs, Toggl.Foundation.MvvmCross/ViewModels/Selectable/SelectableWorkspaceViewModel.cs, Toggl.Foundation.Tests/Sync/States/Push/BaseStates/BasePushEntityStateTests.cs, Toggl.Foundation.Tests/Sync/TestConfigurator.cs, Toggl.Foundation/Analytics/SyncAnalyticsExtensions.cs, Toggl.Giskard/Adapters/BaseRecyclerAdapter.cs, Toggl.Giskard/Adapters/DiffingStrategies/EquatableDiffingStrategy.cs, Toggl.Giskard/Adapters/DiffingStrategies/IDiffingStrategy.cs, Toggl.Giskard/Adapters/DiffingStrategies/IdentifierEqualityDiffingStrategy.cs, Toggl.Giskard/Adapters/SimpleAdapter.cs, Toggl.Giskard/Extensions/Reactive/RecyclerAdapterExtensions.cs, Toggl.Giskard/Toggl.Giskard.csproj, Toggl.Multivac/Ensure.cs, Toggl.Multivac/Extensions/TypeExtensions.cs
This PR deals with three things:
* Relaxes the constraint on a type of SimpleAdapter so it's no longer `IDiffable<T>`, but instead `IEquatable<T>` so that now even primitives can be used.
* Abstracts away the diffing part of things to a strategy.
* Along the way, I have added an extension method to improve readability a bit.
Nothing specific but will help with 🔟.
So that we can use `SimpleAdapter<string>`.
Most of it is selfexplanatory.
I think I have chosen the simplest way possible.
Some renames happened to improve naming. If you have even better naming, please suggest.
Commit by commit.
🔟 people.
=> Use strategy for equality checks in BaseRecyclerAdapter's Diffing algorithm.

Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs, Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs
This fixes the problem where Mvx can't construct SignupViewModel
No created issue
So users can sign up.
By remove IInteractoryFactory from SignupVM and initializing the interactor directly.
Until we sort out the problem with our 🏭 dependency, this is the way.
Nada
Try to sign up I guess
the release manager aka @dshr
=> 😱 temporary fix for signup by removing interactor factory

Toggl.Foundation.MvvmCross/Transformations/TimeEntriesGroupsFlattening.cs, Toggl.Foundation.Tests/MvvmCross/Transformations/TimeEntriesFlatenningTests.cs
Bugfix.
Closes #4788 
Respect user's preferences.
Actually use duration format when flattening.
🤷‍♂️ 
None.
Check the tests.
🦑
=> Respect duration format preferences in GTE

Toggl.Daneel/Services/DialogServiceIos.cs
A small fix to an action sheet bug
Closes #4906 
We don't want our action sheets broken, do we?
By adding the properly needed .Cancel action to the action sheet.
This is the correct Apple-approved way
Try and replicate the behaviour from the issue
iPad crew, just you
=> iPad: Fix bug that caused action dismiss action sheets to break

Toggl.Daneel/Views/EditDuration/DurationFieldTextFormatter.cs
This fixes a potential null exception in DurationFieldTextFormatter.AttributedStringFor.
Closes #5018
By assigning empty string to the variable if it is null.
🦑
=> Prevent null exceptions in DurationFieldTextFormatter.AttributedStringFor

Toggl.Daneel/ViewControllers/Calendar/CalendarViewController.cs
This fixes a crash that's been happening on Daneel 1.21. The issue describes the crash a bit more.
Closes #5016
🦑
=> Fix NullReferenceException in CalendarViewController.ScrollToTop

Toggl.iOS/Presentation/ModalCardPresenter.cs, Toggl.iOS/Presentation/Transition/FromBottomTransitionDelegate.cs, Toggl.iOS/Presentation/Transition/ModalPresentationController.cs, Toggl.iOS/Startup/AppDelegate.cs, Toggl.iOS/Toggl.iOS.csproj, Toggl.iOS/ViewControllers/Reactive/ReactiveTableViewController.cs, Toggl.iOS/ViewControllers/Reactive/ReactiveViewController.cs
This is the last presenter we need for iOS! The entire app can be navigated again.
Closes #4859 
🇬🇧 ➡️ 🚪 
It's another presenter, very similar to the modal dialogs.
This is the only way.
I found at least one ViewModel calling Finish on a different thread (missing ObserveOn maybe?), that caused a crash in ReactiveViewController.Dismiss` so that's why I did the thread marshalling.
🦑
=> Add modal card presenter for iOS

Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS/Info.plist
- Added new Siri Shortcuts and Workflows integration
- Fixed date label on Reports calendar
- Fixed iPad Main View layout
- Fixed some glitches in Login and Signup views
- Fixed possible crash in Calendar
- Fixed possible freeze when coming from background
- Adds copy from clipboard Siri shortcut
- Adds custom reports and start entry Siri shorctus
- Adds section to manage Siri shortcuts
- Adds section for Siri workflows
- Fixes reports selected date label
- Fixes reports calendar dates label not showing shortcuts
- Fixes layout issues in iPad split view
- Fixes glitch in scroll indicator in iPad
- Fixes glitch in password reset view
- Trims spaces from email fields
- Makes keyboard dismissable by swiping
- Shows toggl.com passwords in autofill
- Fixes glitch on entry description field …
=> iOS release 1.22 (Terminus)

build.cake
Without this fix, the iOS ad-hoc build cannot be installed on the device.
=> Fix cake substitutions for iOS adhoc builds

Toggl.Droid/Services/AnalyticsServiceAndroid.cs, Toggl.Droid/Services/FirebaseStopwatchProviderAndroid.cs
When `USE_ANALYTICS` variable is defined, some code is enabled, but their `using`s are missing. 
↩ This is a result of a code styles changes (#5460). Since the `USE_ANALYTICS` variable is not defined in debug, they were reported as the _"unused"_ usings. 🤷‍♂ 
So that we can build the project.
By adding missing usings.
Me and @heytherewill.
=> Fixes build errors when analytics are used

Toggl.Core.UI/Navigation/NavigationService.cs, Toggl.Droid/Properties/AndroidManifest.xml
Reverts one change (albeit not the whole PR) in order to eliminate a possible culprit in [CALI](https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/3390777968u/overview) crashes.
**What is reverted?**
I have reverted one particular part of #5389 that parallelized the initialization of view from the initialization from viewmodel. I'm assuming that in some cases, one depends on another which still isn't properly initialized.
This async code wasn't present in `2.0.1` where it was synchronous. It was introduced between `2.0.1` and `2.1`, so it's possible that it's an issue.
Refs #4230
No 💥 
By waiting for initialization prior to presentation.
In most cases only a slight performance loss on navigation (and startup).
Developers with permissions.
=> ♻ Revert to waiting for initialize to complete

Toggl.iOS/Extensions/TextViewExtensions.cs, Toggl.iOS/Toggl.iOS.csproj, Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
A slightly unsightly fix to a little clash we had between our suggestions and iOS' autocomplete.
Closes #5662
So things look spotless!
By walking across all the subviews of `DescriptionTextView`, finding the offending `UIAutocorrectInlinePrompt` (which is defined in a runtime-only header) by classname, and removing it from the `DescriptionTextView`.
Looked at other options, but due to the runtime-only nature of `UIAutocorrectInlinePrompt` I can't come up with anything.
Reproduce the error from the source issue on `develop`, then here.
All yours!
=> Fix an autocomplete-autocorrect clash

Toggl.Droid/Services/BackgroundSyncJobSchedulerService.cs, Toggl.Droid/Services/BackgroundSyncServiceAndroid.cs
This disables background sync again, but this time only on Android 10 ( I guess we can call this a progress) 
Closes #6040
We don't want background sync related crashes on Android 10 devices
I reused the disabling code from the past but only for Android 10+
We couldn't find a less drastic solution.
Background sync won't work on all Android 10 devices
Me
=> Disable background sync for Android 10

build.cake
This is a new way to increase versionCodes/bundleVersion for AppStore/PlayStore builds
Closes #6086
We want to take more control over our version codes
Parsing the tag name with regex ( thanks to @kornelijepetak and @juanlaube )
Show me
I don't even know how to test this properly :-) 
Integration tests:  - do not merge this branch unless these tests are passing.
Feel free
=> Version code generation based on tag name

build.cake
Make maintenance part of the tag optional again
Closes #6184
We want to be able to do tags like `android-2.5` again
A small change in regexp to make the maintenance part optional
Anyone
=> Make maintenance part of the tag optional again

.github/ISSUE_TEMPLATE/d-manual-test-template.md
For a long time, we had this 'taken project name error' check broken on Android because nobody was testing this. Users shouldn't be able to add new project with the existing project name espetially if that existing project name has the same client as well. (Android currently checks only name, web checks both... ) 
We don't want another regression.
Anyone
=> Add taken project name error check

Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs
Fixes start entry description text color in dark mode.
Closes #6245 
I just set the color of the text when preparing the view. It worked when you setup a project or tag, because then it takes the color from the attributed text, but not when the user starts typing.
Do it!
=> Fix start entry description text color

Toggl.Droid/DebugHelpers/ErrorTriggeringFragment.cs, Toggl.Droid/Fragments/SelectDefaultWorkspaceFragment.ViewBinds.cs, Toggl.Droid/Properties/AndroidManifest.xml, Toggl.Droid/Resources/layout/SelectDefaultWorkspaceFragment.axml
- Added sync status next to the logout button
- Fixed a bug which made syncing appear to take forever
- Fixed a crash that occurred when filtering lists
- Fixed visual glitches in the pie chart
- Fixed an empty view presented when selecting a default workspace
- Fixed incorrect copy on the login page
- Fixed rating view not being presented
- Made background sync use light sync, instead of full sync
- Added analytic events for calendar selection
- Enabled analytic events for background syncing
https://github.com/toggl/mobileapp/compare/android-2.4.1...android-2.5-faloodeh
=> Android 2.5 Faloodeh

Toggl.iOS/Autocomplete/AutocompleteExtensions.cs, Toggl.iOS/ViewControllers/StartTimeEntryViewController.xib
A rather hack-like fix to the problem of creating projects and tags from the Start TE view when using an RTL language.
Closes #5561
We care about all our users.
We use the Xamarin ver of `attributes(at:longestEffectiveRange:in:)` to extract the existing tag/project substrings out of the big description string. The problem happens when we mix RTL languages with non-RTL chars, like `@` and `#` — the method treats them as separate segments. This way, instead of getting a single string for `TE Name @newproj`, we get three: `TE Name`, `@` and `newproj`. In this implementation I loop over the output spans and look for spans, preceded by spans containing `@` or `#`. Then I merge these spans into one new `QueryTextSpan`, which is then processed correctly by our pipeline.
This seems like the most …
=> Fix iOS RTL project and tag creation

Toggl.iOS.SiriExtension.UI/Toggl.iOS.SiriExtension.UI.csproj, Toggl.iOS.SiriExtension/Toggl.iOS.SiriExtension.csproj, Toggl.iOS.TimerWidgetExtension/Toggl.iOS.TimerWidgetExtension.csproj, Toggl.iOS/Toggl.iOS.csproj
This enables the Linker + LLVM in every iOS project
We don't really wanna ship 200MB binaries
Enabling Linker All + LLVM on all iOS projects
This will need some **really** thorough testing, since problems might have lurked in
@juanlaube
=> Reduce the size of iOS artifacts

Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist, Toggl.iOS/Presentation/Transition/ModalPresentationController.cs
- Added new today extension for timer and suggestions
- Improved RTL language support
- Fixed dates formatting issues
- Fixed a bug in Siri shortcuts
- Fixed a bug that made deleted time entries reappear
- Other stability and performance improvements
https://github.com/toggl/mobileapp/compare/ios-2.6-5...release/ios-2.6.1-grapefruit-hotfix
=> iOS 2.6.1 Grapefruit hotfix

Toggl.Droid/Resources/layout/MainLogCell.axml
This PR was created by cherry picking the commit ac8b622ef975eae669c0938e8d5a76e02c3e808a
Closes #Nothing
To have nice paddings/margins.
It cherry-picks the commit generated by #6602 
This commit could be safely cherry-picked because it doesn't touch anything androidX related :)
I'll handle it.
=> Cherry pick #6602 for android 2.7

Toggl.Droid/Extensions/FloatingActionButtonExtensions.cs, Toggl.Droid/Fragments/MainFragment.cs
This PR was created by cherry picking the commit 1070cfa51d80f157f68ab59c3360f60379732890
Closes #Nothing
This is a best-effort bug fix to prevent the user from having no start/create time entry button in the main log (check #6584)
It cherry-picks the commit generated by #6597 
This commit could be safely cherry-picked because it doesn't touch anything androidX related :)
I'll handle it.
=> Cherry pick #6597 for android 2.7

Toggl.Core.Tests/Services/UpdateRemoteConfigCacheServiceTests.cs, Toggl.Core/Extensions/RemoteConfigExtensions.cs, Toggl.Core/Services/IFetchRemoteConfigService.cs, Toggl.Core/Services/IRemoteConfigService.cs, Toggl.Core/Services/IUpdateRemoteConfigCacheService.cs, Toggl.Core/Services/RemoteConfigService.cs, Toggl.Core/Services/UpdateRemoteConfigCacheService.cs, Toggl.Droid/Resources/xml/RemoteConfigDefaults.xml, Toggl.Droid/Services/FetchRemoteConfigServiceAndroid.cs, Toggl.Shared.Tests/January2020CampaignConfigurationTests.cs, Toggl.Shared/January2020CampaignConfiguration.cs, Toggl.iOS/RemoteConfigDefaults.plist, Toggl.iOS/Services/FetchRemoteConfigServiceIos.cs
This PR adds a remote config option as it is specified in the referenced issue.
Ref #6616 
We want A/B testing.
It's quite a lot of code for something so simple 🤔 
🦑
=> January campaign: Remote config

Toggl.Droid/Fragments/January2020CampaignFragment.cs
This makes campaign dialog not dismissible when tapping outside.
Ref #6616
To make sure the users see the campaign, avoiding mistaps when the campaign dialog shows up.
Ref https://github.com/toggl/mobileapp/issues/6616#issuecomment-558209945
Internal conversation: /archives/C02APMYTM/p1574697864231100
The change is very simple, take a look at the single line change.
🦑 it
=> Make campaign dialog not dismissible when tapping outside

Toggl.iOS.Shared/SharedStorage.TimeEntries.cs, Toggl.iOS.TimerWidgetExtension/TodayViewController.cs
A bugfix.
Closes #6871 
No (fake) error messages! 🙈 
When a TE was stopped, the observer tried to update the running entity, but it didn't account for TE stopping 🙈 
🦑
=> Prevent null ref excepton in the iOS Widget

Toggl.Droid/Fragments/Calendar/CalendarDayViewPageFragment.cs
This fixes the calendar day view bindings that were being done a little too late in the `CalendarDayViewPageFragment`.
Closes #6974
So that the calendar works as expected.
By moving the calendar day view bindings to where the calendar day view bindings should be.
This is the way.
Do a functional test please.
🦑 it please.
=> Fix calendar day view lazy bindings

Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist
The iOS 2.12 release.
Closes: #7139
- Added support for tasks in Siri Shortcuts
- Fixed a bug in calendar settings when requesting permissions
- Fixed several bugs in the calendar view
- Other syncing and performance improvements
https://github.com/toggl/mobileapp/compare/ios-2.11-2...release/ios-2.12-mango
🚫Nope
=> iOS 2.12: Mango

Toggl.Core.Tests/UI/ViewModels/LoginViewModelTests.cs, Toggl.Core.Tests/UI/ViewModels/SignupViewModelTests.cs, Toggl.Core.Tests/UserAccessManager/UserAccessManagerTests.cs, Toggl.Core.UI/ViewModels/LoginViewModel.cs, Toggl.Core.UI/ViewModels/SignupViewModel.cs, Toggl.Core.UI/Views/IThirdPartyTokenProvider.cs, Toggl.Core/Helper/ThirdPartyLoginInfo.cs, Toggl.Core/UserAccessManager/IUserAccessManager.cs, Toggl.Core/UserAccessManager/UserAccessManager.cs, Toggl.Droid/Activities/ReactiveActivity.ThirdPartyTokenProvider.cs, Toggl.Droid/Fragments/Calendar/CalendarDayViewPageFragment.PermissionHandler.cs, Toggl.Droid/Fragments/ReactiveDialogFragment.cs, Toggl.Droid/Fragments/ReactiveTabFragment.cs, Toggl.Networking.Tests/ApiClients/UserApiTests.cs, Toggl.Networking/ApiClients/Interfaces/IUserApi.cs, Toggl.Networking/ApiClients/UserApi.cs, Toggl.iOS/ViewControllers/Reactive/ReactiveTableViewController.cs, Toggl.iOS/ViewControllers/Reactive/ReactiveViewController.ThirdPartyTokenProvider.cs
Sends the fullname on sign up with Apple.
Closes #7166 
Because otherwise the username will be taken from the email address and we don't want to send emails to users saying "Hi asd987asd, Welcome to Toggl..."
Fetching the fullname from the returned data in the apple token provider.
This is the way.
None.
If you are going to test this, make sure to unlink toggl from your appleid first, otherwise it might not work (and that's fine, it's how sign in with Apple works).
⛔️ No
=> Send fullname if possible on sign up with Apple

Toggl.Core.Tests/UI/ViewModels/OnboardingViewModelTests.cs, Toggl.Core.UI/ViewModels/OnboardingViewModel.cs, Toggl.iOS/Presentation/NavigationPresenter.cs
Fixes the google signup in the onboardingVC
none
We kind of want users to signup.
I changed the NavigationPresenter to present modally if the presentingVC is not a navigationController. Fixed onboardingVC to actually signup after failed login.
The issue is that the from the moment the login attempt starts there is a considerable time passing until the error is returned and the signup starts (by showing the country selection UI). No loading UI at this point makes the app look like it is doing nothing and waiting for user to tap buttons.
Create a google account and try to signup
Ping me if you need help setting up the goole signup in debug.
:squid:
=> Fix google signup

Toggl.iOS/Resources/Colors.xcassets/ReportsBarChartFilled.colorset/Contents.json, Toggl.iOS/Resources/Colors.xcassets/ReportsBarChartTotal.colorset/Contents.json
Interchanges the billable and non billable colors for the reports bar view. Those were set the wrong way.
Closes #7202
people called us out on twitter
Interchanges the billable and non billable colors for the reports bar view
check agains web
me
=> 💄 Fix reports segment colors

Toggl.Shared/Resources.fr.resx, Toggl.Shared/Resources.ja.resx, Toggl.Shared/Resources.pt.resx
An attempt to fix https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/354678555u/overview
Closes #
Copy over the English strings to all other languages.
Because we don't have all the actual translations yet.
Validate the app doesn't crash in the start TE screen in one of the custom languages.
Anyone
=> 🐛 Fix a crash happening due to string translation missing

Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist
This is the iOS 2.19 release PR.
Changelog:
```
Changed appearance for Toggl Track rebrand.
Added the start button and running time entry card to the calendar view.
Added more information to items in the calendar view.
Added support for navigating to more dates in the calendar view.
Changed the tabs order.
```
Diff: https://github.com/toggl/mobileapp/compare/ios-2.18..ios-2.19
🚫
=> iOS 2.19 - Tomato

Toggl.Droid/Properties/AndroidManifest.xml, Toggl.Droid/Views/Calendar/CalendarDayView.Events.cs
At hotfix for Android 2.19. The only significant crash is caused by an invalidation of the calendar view in a thread that is not the main thread.
We don't want crashes.
Subscribing to that current date time observable on the main thread.
This is the way.
None.
See if you can reproduce the issue first, I couldn't but it's obviously happening.
🚫 NO!
=> Release/android 2.19.1 tiramisu hotfix

Toggl.Shared/Resources.fr.resx, Toggl.Shared/Resources.ja.resx, Toggl.Shared/Resources.pt.resx, Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Cells/Calendar/CalendarItemView.cs, Toggl.iOS/Info.plist
A hotfix for iOS 2.19. The crash happens on iOS < 13 because I used an iOS 13 only API 🙈 
We don't want crashes.
The crash happens when drawing the running time entry background pattern on the calendar items, I changed this to the old way instead of using the fancy new API.
This is the way.
None.
🚫 NO!
=> Release/ios 2.19.1 tomato hotfix
