Toggl.Multivac/WorkspaceFeatureId.cs
I received this value from the `me/features` endpoint. I think it should be added to the Enum too.
=> Update WorkspaceFeatureId to match backend returned list

Toggl.Daneel/Info.plist, Toggl.Daneel/ViewSources/CreateSuggestionGroupedTableViewSource.cs
Changelog:
```
- Added sign-up
- Added creation of clients and projects
- Added warning when time entry description exceeds limit
- Added confirmation when deleting time entries
- Fixed log not updating correctly overnight
- Fixed deleted tags not syncing correctly
- Various fixes and improvements
```
=> Beta 2 (0.2) - Luna

Toggl.Daneel/Info.plist, Toggl.Daneel/Presentation/TogglPresenter.cs, Toggl.Daneel/ViewControllers/MainViewController.cs, Toggl.Foundation.MvvmCross/Toggl.Foundation.MvvmCross.csproj, Toggl.Foundation/Toggl.Foundation.csproj, Toggl.Multivac/Toggl.Multivac.csproj, Toggl.PrimeRadiant.Realm/Toggl.PrimeRadiant.Realm.csproj, Toggl.PrimeRadiant/Toggl.PrimeRadiant.csproj, Toggl.Ultrawave/Toggl.Ultrawave.csproj
```
- Added reports
- Fixed Asian keyboard input adding too many characters
- Fixed app freezing when starting/stopping/continuing for some users
- Fixed timer not updating correctly, leading to crash when using start/stop button
- Improved autocompletion and suggestions in a number of small ways
- Improved handling of errors when pulling data
- Improved syncing to report errors faster
- Improved animations of time entry details view
- Various other UI fixes and improvements
```
=> Release 1.1 Mars

Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs
Closes #1447 
Make a functional test when reviewing.
Squash whenever
=> Prevent null reference exception in manual mode

Toggl.Daneel/Info.plist, Toggl.Daneel/PlatformConstants.cs, Toggl.Daneel/Startup/AppDelegate.cs, Toggl.Daneel/ViewControllers/EditDurationViewController.cs, Toggl.Daneel/ViewControllers/EditTimeEntryViewController.cs, Toggl.Daneel/ViewControllers/EditTimeEntryViewController.xib, Toggl.Daneel/ViewControllers/LoginViewController.cs, Toggl.Daneel/ViewControllers/MainViewController.cs, Toggl.Daneel/ViewControllers/MainViewController.xib, Toggl.Daneel/ViewControllers/SelectProjectViewController.cs, Toggl.Daneel/ViewControllers/SelectTagsViewController.cs, Toggl.Daneel/ViewControllers/SettingsViewController.cs, Toggl.Daneel/ViewControllers/SettingsViewController.xib, Toggl.Daneel/Views/MainScrollView.cs, Toggl.Foundation.MvvmCross/ViewModels/EditTimeEntryViewModel.cs, Toggl.Foundation.MvvmCross/ViewModels/SettingsViewModel.cs, Toggl.Foundation.MvvmCross/ViewModels/StartTimeEntryViewModel.cs, Toggl.Foundation.Tests/MvvmCross/ViewModels/EditTimeEntryViewModelTests.cs
:shipit: 🚀  ☀️  
```
- Added manual mode
- Added time edit wheel
- Added in-app feedback function
- Added 'today' and 'yesterday' shortcuts to reports calendar
- Added password validation during signup
- Fixed input bugs with some Asian language keyboards
- Fixed crashes and empty log that could happen when tapping start/stop/continue buttons multiple times quickly
- Fixed ignoring local time zones for date display
- Fixed syncing bar sometimes displaying wrong state when offline
- Fixed leak that could cause the app to use more battery than needed
- Various other fixes and improvements
```
=> Release 1.3 - Saturn

Toggl.Daneel/ViewControllers/EditProjectViewController.cs, Toggl.Daneel/ViewControllers/EditProjectViewController.designer.cs, Toggl.Daneel/ViewControllers/EditProjectViewController.xib
=> Make the whole private switch row tappable in the edit project view

Toggl.Giskard/Properties/AndroidManifest.xml
I'm not even going to make a changelog right now. Maybe tomorrow.
=> Giskard 0.2 - Helium

Toggl.Giskard/Fragments/ReportsCalendarFragment.cs
=> Fix reports calendar row height calculation

Toggl.Foundation/Login/ILoginManager.cs, Toggl.Foundation/Login/LoginManager.cs, Toggl.Ultrawave/ApiClients/Interfaces/IUserApi.cs, Toggl.Ultrawave/ApiClients/UserApi.cs
=> :construction: Make country id non-nullable for API calls

Toggl.Giskard/Resources/layout/LoginActivity.axml, Toggl.Giskard/Resources/layout/SignUpActivity.axml, Toggl.Giskard/Resources/values/Colors.xml
Closes #2276 
Closes #2277
🦑 whenever
=> Fix TextEdit underline color in login and sign up screens

Toggl.Daneel/ViewControllers/SignupViewController.cs, Toggl.Daneel/ViewControllers/SignupViewController.designer.cs, Toggl.Daneel/ViewControllers/SignupViewController.xib, Toggl.Foundation.MvvmCross/ViewModels/SignupViewModel.cs, Toggl.Foundation.Tests/MvvmCross/ViewModels/SignupViewModelTests.cs
=> Shake the invalid fields for signup

Toggl.Giskard/Activities/MainActivity.cs, Toggl.Giskard/Extensions/OnboardingExtensions.cs, Toggl.Giskard/Extensions/PopupOffsets.cs, Toggl.Giskard/Extensions/PopupWindowWithDefaultGravityExtenstions.cs, Toggl.Giskard/Helper/PopupWindowFactory.cs, Toggl.Giskard/Resources/layout/TooltipWithRightArrow.axml, Toggl.Giskard/Resources/values/Strings.xml, Toggl.Giskard/Toggl.Giskard.csproj
Part of #1646
I'll create one PR for each step described in the issue.
This is the PR for the first step.
Merge without squashing please, this PR is not targeting develop. It will be easier to revert changes on the way if something bad happens.
=> Android onboarding phase 1 step 1

Toggl.Giskard/Adapters/SegmentedRecyclerAdapter.cs
Fixes #2598 
After syncing, at some point in time, it seems that collection was empty, so it would crash the get item.
`GetItem` should return null not only if the Collection is null but also if it was empty as there are no items to show.
Also, access to `headerIndexes` should be protected in all places, not only in some.
=> Fix sync scroll bug

Toggl.Giskard/Autocomplete/AutocompleteExtensions.cs, Toggl.Giskard/Properties/AndroidManifest.xml
_Nitrogen boils at ~77 degrees Kelvin._
Changelog:
```
- Improved UI for larger font sizes
- Fixed crash related to have two running time entry
- Fixed crash when leaving the app while editing a time entry
- Various other fixes and improvements
```
=> Giskard 1.1 - Nitrogen

Toggl.Giskard/Properties/AndroidManifest.xml, Toggl.Giskard/Startup/SplashScreen.cs
_giving our users a breath of fresh air from crashes and broken layouts_
Did you know that oxygen is a most dangerous molecule? In its liquid form, it can kill instantly, while at higher temperatures it easily causes endothermic reactions with other chemicals due to its high electron affinity.
```
- Fixed crash when scrolling the time entry log while syncing
- Fixed descriptions being cut off with RTL layout
- Fixed clients and tasks overlapping in time entry log
- Fixed timer display with varying font and display sizes
- Fixed login/signup screen layout on smaller phones
- Removed broken landscape mode in time entry edit view
- Various other fixes and improvements
```
=> Giskard 1.2 - Oxygen

docs/siri.md
Adding prerequisites section for modifying Siri intents.
Anyone
=> 📃 Adding prerequisites section

Toggl.Daneel/Cells/Calendar/SelectableUserCalendarViewCell.cs, Toggl.Daneel/Cells/Calendar/SelectableUserCalendarViewCell.designer.cs, Toggl.Daneel/Cells/Calendar/SelectableUserCalendarViewCell.xib, Toggl.Daneel/Info.plist, Toggl.Daneel/ViewControllers/EditDurationViewController.cs, Toggl.PrimeRadiant.Realm/Models/RealmConstructors.cs
```
- Added the brand new calendar integration. Now you can:
- View time entries and events from the selected calendars alongside
- Create new time entries from calendar events
- Create new time entries by dragging on the calendar view
- Edit new time entries with a tap and hold gesture
- Receive notifications before a calendar event starts
Other:
- Improved Siri Shortcuts integration, you can now create time entries including the project and tags information
```
Sirius is also known colloquially as the "Dog Star", reflecting its prominence in its constellation, Canis Major.
https://github.com/toggl/mobileapp/compare/daneel-1.11...sirius
=> Daneel 1.12 - Sirius

Toggl.PrimeRadiant.Tests/Settings/SettingsStorageTests.cs, Toggl.PrimeRadiant/Settings/IUserPreferences.cs, Toggl.PrimeRadiant/Settings/SettingsStorage.cs
This PR adds configuration of the working hours.
This PR does not add any UI and it doesn't use the settings for any effect.
Closes #3629 
None.
🦑
=> Calendar working hours settings

Toggl.Giskard/Extensions/ContextExtensions.cs, Toggl.Giskard/Extensions/DrawableExtensions.cs, Toggl.Giskard/Extensions/MotionEventExtensions.cs, Toggl.Giskard/Extensions/PointExtensions.cs, Toggl.Giskard/Resources/drawable/ic_play.xml, Toggl.Giskard/Resources/drawable/ic_stop.xml, Toggl.Giskard/Toggl.Giskard.csproj, Toggl.Giskard/Views/EditDuration/Shapes/Arc.cs, Toggl.Giskard/Views/EditDuration/Shapes/Cap.cs, Toggl.Giskard/Views/EditDuration/Shapes/Dot.cs, Toggl.Giskard/Views/EditDuration/Shapes/Wheel.cs, Toggl.Giskard/Views/EditDuration/WheelForegroundView.cs
This is part of the droid wheel.
When done, it should have:
Basic Interface:
The view itself:
Closes #4144 
To complete the wheel component for android.
It's an adaptation of the iOS version, considering the android differences.
It looks nice this way. After some cleanup it should be even easier to read than it is when I created the wip.
None.
You can see the view if you put it in some layout inside the app. You have to specify the width and height of the view. Anything like:
```
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"
android:layout_height="wrap_content"
android:layout_width="match_parent">
<toggl.giskard.views.WheelForegroundView
android:layout_marginTop="40dp" …
```
=> Droid wheel: Base wheel (ForegroundWheel)

Toggl.Giskard/Properties/AndroidManifest.xml
```
- Added a screen for editing time using the time wheel
- Fixed tags being created with a truncated name
- Fixed swiped-to-delete time entries not being deleted
- Improved the sync reliability
- Lists are now sorted alphabetically
- Some other under the hood fixes and improvements
```
https://github.com/toggl/mobileapp/compare/giskard-1.10.3...giskard-1.11
https://github.com/toggl/mobileapp/compare/giskard-1.11...giskard-1.11.1
🚫 Only the release manager once the app is released to the users.
=> Giskard 1.11.1 (Chlorine Hotfix)

Toggl.Ultrawave.Tests.Integration/UserApiTests.cs
✅ Fix /signup tz integration test
No created issue.
Changing the assertion
This is the intended behavior.
Nope
Integration tests: https://app.bitrise.io/build/2bc506cec97f38b1 - do not merge this branch unless these tests are passing.
:doit:
=> ✅ Fix /signup tz integration test

Toggl.Giskard/Fragments/CalendarPermissionDeniedFragment.ViewBinds.cs, Toggl.Giskard/Fragments/CalendarPermissionDeniedFragment.cs, Toggl.Giskard/Resources/layout/CalendarPermissionDeniedFragment.axml, Toggl.Giskard/Resources/values/Strings.xml, Toggl.Giskard/Toggl.Giskard.csproj
This adds the dialog fragment to ask for calendar permissions when it was previously denied.
Closes #4465 
We want users to enable calendars.
It's just another dialog fragment.
None.
Try it!
🦑
=> Calendar permission denied fragment

Toggl.Daneel/Views/Reports/ReportsHeaderView.cs
Trying to solve conflicts
pad crew
=> Conflict resolution

Toggl.Droid/Properties/AndroidManifest.xml
Final mergeback before merging.
iPad ppl
=> iPad: The Ultimate Mergeback

Toggl.Droid/Properties/AndroidManifest.xml
```
- Fixed a calendar bug in Reports View
- Prevent deletions caused by accidental swiping
- Improve user interface during project creation process
```
[giskard-1.14...giskard-1.15](https://github.com/toggl/mobileapp/compare/giskard-1.14...giskard-1.15)
=> Giskard 1.15 - Scandium

Toggl.iOS/Views/Suggestions/SuggestionsView.cs
Merging develop for the last time before squashing into it.
🎙
=> Siri. Merge develop into project branch

Toggl.Core.Tests/Interactors/TimeEntry/ContinueTimeEntryInteractorTests.cs, Toggl.Core.Tests/UI/ViewModels/CalendarPageViewModelTests.cs, Toggl.Core.UI/ViewModels/Reports/ReportsViewModel.cs, Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarLastMonthQuickSelectShortcut.cs, Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarLastWeekQuickSelectShortcut.cs, Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarLastYearQuickSelectShortcut.cs, Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarThisMonthQuickSelectShortcut.cs, Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarThisWeekQuickSelectShortcut.cs, Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarThisYearQuickSelectShortcut.cs, Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarTodayQuickSelectShortcut.cs, Toggl.Core.UI/ViewModels/ReportsCalendar/QuickSelectShortcuts/ReportsCalendarYesterdayQuickSelectShortcut.cs, Toggl.Core.UI/ViewModels/ReportsCalendar/ReportsCalendarDayViewModel.cs, Toggl.Core.UI/ViewModels/ReportsCalendar/ReportsCalendarPageViewModel.cs, Toggl.Core/Analytics/BaseAnalyticsService.cs, Toggl.Core/Analytics/ContinueTimeEntryOrigin.cs, Toggl.Core/Analytics/IAnalyticsService.cs, Toggl.Core/Interactors/TimeEntry/ContinueTimeEntryInteractor.cs, Toggl.Droid.Tests.UI/Configuration.cs, Toggl.Droid/Resources/layout/ReportsFragmentHeader.axml, Toggl.Droid/Resources/layout/StartTimeEntryActivity.axml, Toggl.Droid/Resources/layout/StartTimeEntryActivityTimeEntryCell.axml, Toggl.Droid/Views/BarChartView.cs, Toggl.Shared/Extensions/DateTimeOffsetExtensions.cs, Toggl.Shared/Resources.resx, Toggl.iOS.Tests.UI/Configuration.cs, Toggl.iOS/Entitlements.plist
One last mergeback
Only myself
=> MVExit final mergeback

Toggl.Core.UI/Navigation/ViewModelLoader.cs, Toggl.Core.UI/ViewModels/Settings/Siri/PasteFromClipboardViewModel.cs, Toggl.Core.UI/ViewModels/Settings/Siri/SiriShortcutsCustomTimeEntryViewModel.cs, Toggl.Droid/Properties/AndroidManifest.xml
- Fixed tasks not being selectable when editing time entries
- Fixed tasks not being suggested when creating time entries
- Fixed several UI glitches on smaller resolution phones
- Fixed app shortcuts not appearing when long pressing the app launcher
- Fixed a bug that made the app not sync with our servers
- Various other under the hood improvements and fixes
- Fixed tasks not being selectable when editing time entries
- Fixed tasks not being suggested when creating time entries
- Fixed reports UI on small phones
- Changed the app logo
- Fixed app shortcuts not appearing when long pressing the app launcher
- Fixed a bug that made the app not sync with our servers
- Performance improvements
- Changed app icons
- Completely removed MvvmCross from our apps
- Fixed the race condition that …
=> Android 2.0 Release Candidate 2 - Alfajor

Toggl.Droid/BroadcastReceivers/SmartAlertCalendarEventBroadcastReceiver.cs, Toggl.Droid/Services/NotificationServiceAndroid.cs
An other merge back for suggestions
🔮 only
=> Suggestion merge back

Toggl.Core.Tests/UI/ViewModels/EditTimeEntryViewModelTests.cs, Toggl.Core.Tests/UI/ViewModels/TimeEntriesViewModelTests.cs, Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs, Toggl.Core.UI/ViewModels/TimeEntriesViewModel.cs, Toggl.Core/Analytics/BaseAnalyticsService.cs, Toggl.Core/Analytics/DeleteTimeEntryOrigin.cs, Toggl.Core/Analytics/IAnalyticsService.cs, Toggl.Droid/Services/CalendarServiceAndroid.cs, Toggl.Droid/Startup/TogglApplication.cs, Toggl.Droid/Toggl.Droid.csproj, Toggl.iOS/Extensions/Reactive/UIButtonExtensions.cs, Toggl.iOS/Extensions/Reactive/UIViewExtensions.cs, Toggl.iOS/Startup/AppDelegate.cs, Toggl.iOS/Toggl.iOS.csproj, Toggl.iOS/ViewControllers/MainViewController.cs, docs/certificate.md
A mergeback
To have bitrise builds working
```
git checkout develop
git pull
git checkout projects/i18n
git pull
git checkout -b i18-mergeback-1
git merge develop
```
Don't. Let me do it.
=> Mergeback develop into i18n project

Toggl.Droid/Activities/EditProjectActivity.cs, Toggl.Droid/Autocomplete/ProjectTokenSpan.cs, Toggl.Droid/Autocomplete/TagsTokenSpan.cs, Toggl.Droid/Properties/AndroidManifest.xml, Toggl.Droid/Resources/drawable/EditTextCursor.xml, Toggl.Droid/Resources/layout/EditTimeEntryActivity.axml, Toggl.Droid/Resources/layout/StartTimeEntryActivity.axml, Toggl.Droid/Toggl.Droid.csproj
- Improved the toolbar colors across the app to be more consistent
- Improved time entry suggestions
- Fixed the suggestions to not show archived project
- Fixed a bug in the edit duration view
- Fixed a crash when selecting tags
- Other performance and stability improvements
https://github.com/toggl/mobileapp/compare/android-2.1.6...android-2.2
=> Android 2.2 - Crème brûlée

Toggl.Droid/Activities/SelectProjectActivity.cs, Toggl.Droid/Activities/SelectTagsActivity.cs, Toggl.Shared/Resources.resx, Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS/Info.plist, Toggl.iOS/ViewControllers/MainViewController.cs
A mergeback from develop into i18n.
Part of #5747 
To merge the project into develop without conflicts.
```
git checkout project/i18n
git checkout -b i18n-mergeback-3
git merge develop
```
There was only a conflict with the `Resources.resx` file. Feel free to check it out.
Merge it.
=> Merge develop back into I18n (3rd time)

Toggl.Core.UI/Helper/EditTimeEntryInfo.cs, Toggl.Core.UI/ViewModels/MainViewModel.cs, Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs, Toggl.Droid/Fragments/MainFragment.cs, Toggl.Droid/Properties/AndroidManifest.xml, Toggl.iOS/ViewControllers/MainViewController.cs
- Improved performance of saving time entries
- Fixed crashes that happened when the app returned to foreground
- Added a page for app licenses
- Various UI tweaks and under the hood improvements
https://github.com/toggl/mobileapp/compare/android-2.2.1...android-2.3
=> Android 2.3 - Dulce de Leche

Toggl.Core.UI/ViewModels/Base/ViewModel.cs, Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs, Toggl.Core.UI/ViewModels/LoginViewModel.cs, Toggl.Core.UI/ViewModels/Settings/SendFeedbackViewModel.cs, Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs, Toggl.Droid/Properties/AndroidManifest.xml, Toggl.Droid/Resources/layout/ReportsCalendarView.axml, Toggl.Droid/Resources/layout/ReportsFragment.axml, Toggl.Droid/Resources/layout/SendFeedbackActivity.axml, Toggl.Droid/Resources/layout/SettingsFragment.axml, Toggl.Droid/Views/BarChartView.cs
- Improved performance of saving time entries
- Fixed crashes that happened when the app returned to foreground
- Added a page for app licenses
- Various UI tweaks and under the hood improvements
- Fixed a crash happening when linking calendars
- Fixed sporadic crashes in the login flow
- Fixed crashes in the reports view
https://github.com/toggl/mobileapp/compare/android-2.3-1...android-2.3.1
=> Android 2.3.1 - Dulce de Leche Hotfix

Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS/Info.plist, Toggl.iOS/ViewControllers/Common/SelectorViewController.cs, Toggl.iOS/ViewControllers/Settings/SettingsViewController.cs, Toggl.iOS/ViewSources/Generic/Common/SelectorTableViewSource.cs, Toggl.iOS/Views/Log/RefreshControl.cs
- Implemented Handoff to web
- Made new projects private by default
- Added the ability to sync archived projects
- Fixed some issues with layout on the Settings screen
- Performance improvements
https://github.com/toggl/mobileapp/compare/ios-2.3-1...ios-2.4-elderberry
=> iOS 2.4 - Elderberry

Toggl.Core.Tests/UI/ViewModels/CalendarSettingsViewModelTests.cs, Toggl.Core.Tests/UI/ViewModels/ForgotPasswordViewModelTests.cs, Toggl.Core.Tests/UI/ViewModels/SelectUserCalendarsViewModelBaseTests.cs, Toggl.Core.Tests/UI/ViewModels/SelectUserCalendarsViewModelTests.cs, Toggl.Core.UI/Navigation/ViewModelLoader.cs, Toggl.Core.UI/ViewModels/Calendar/SelectUserCalendarsViewModel.cs, Toggl.Core.UI/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs, Toggl.Core.UI/ViewModels/ForgotPasswordViewModel.cs, Toggl.Core.UI/ViewModels/Settings/CalendarSettingsViewModel.cs, Toggl.Core/Analytics/BaseAnalyticsService.cs, Toggl.Core/Analytics/IAnalyticsService.cs, Toggl.Droid/Services/BackgroundSyncJobSchedulerService.cs, Toggl.Shared.Tests/RatingViewCriterionExtensionsTests.cs, Toggl.Shared/Extensions/DictionaryExtensions.cs, Toggl.Shared/RatingViewConfiguration.cs, Toggl.Storage/Settings/IOnboardingStorage.cs, Toggl.Storage/Settings/SettingsStorage.cs, Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs, Toggl.iOS/ViewControllers/ForgotPasswordViewController.cs, Toggl.iOS/ViewControllers/ForgotPasswordViewController.xib, Toggl.iOS/ViewControllers/Settings/CalendarSettingsViewController.cs
=> Merge back to Calendar project

Toggl.Core.Tests/UI/ViewModels/CalendarSettingsViewModelTests.cs, Toggl.Core.Tests/UI/ViewModels/ForgotPasswordViewModelTests.cs, Toggl.Core.Tests/UI/ViewModels/SelectUserCalendarsViewModelBaseTests.cs, Toggl.Core.Tests/UI/ViewModels/SelectUserCalendarsViewModelTests.cs, Toggl.Core.UI/Navigation/ViewModelLoader.cs, Toggl.Core.UI/ViewModels/Calendar/SelectUserCalendarsViewModel.cs, Toggl.Core.UI/ViewModels/Calendar/SelectUserCalendarsViewModelBase.cs, Toggl.Core.UI/ViewModels/ForgotPasswordViewModel.cs, Toggl.Core.UI/ViewModels/Settings/CalendarSettingsViewModel.cs, Toggl.Core/Analytics/BaseAnalyticsService.cs, Toggl.Core/Analytics/IAnalyticsService.cs, Toggl.Droid/Services/BackgroundSyncJobSchedulerService.cs, Toggl.Shared.Tests/RatingViewCriterionExtensionsTests.cs, Toggl.Shared/Extensions/DictionaryExtensions.cs, Toggl.Shared/RatingViewConfiguration.cs, Toggl.Storage/Settings/IOnboardingStorage.cs, Toggl.Storage/Settings/SettingsStorage.cs, Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs, Toggl.iOS/ViewControllers/ForgotPasswordViewController.cs, Toggl.iOS/ViewControllers/ForgotPasswordViewController.xib, Toggl.iOS/ViewControllers/Settings/CalendarSettingsViewController.cs
Merge back from develop, no conflicts 🙂 
Merge, not squash
=> Widgets mergeback

Toggl.iOS/Presentation/RootPresenter.cs, Toggl.iOS/ViewControllers/OutdatedAppViewController.cs, Toggl.iOS/ViewControllers/OutdatedAppViewController.xib
Closes #6258 
To force the app to show the view:
- go to settings
- long press the "Settings" title at the top
- select either "Outdated client error" or "Outdated API error"
- the `OutdatedAppViewController` will open
This is how it'll look like:
🦑
=> Dark mode: outdated app view

Toggl.Droid/Toggl.Droid.csproj, Toggl.Droid/packages.config, Toggl.iOS/Toggl.iOS.csproj, Toggl.iOS/packages.config
A merge back from develop, no conflicts.
🦑
=> Widgets final mergeback (again)

Toggl.Droid/Resources/drawable/ic_copy.xml, Toggl.Droid/Resources/layout/ContextualMenuActionCell.axml, Toggl.Droid/Resources/values/Colors.xml, Toggl.Droid/ViewHolders/CalendarMenuActionCellViewHolder.cs
This PR was created by cherry picking the commit 05213726470a83b07ae1faa5ba0804a508ce5d2c
Closes #Nothing
To have a good looking calendar view on android.0
It cherry-picks the commit generated by #6581
This commit could be safely cherry-picked because it doesn't touch anything androidX related :)
I'll handle it.
=> Cherry pick #6581 for android 2.7

.github/CODEOWNERS, Toggl.Core.Tests/UI/ViewModels/NotificationSettingsViewModelTests.cs, Toggl.Core.UI/Services/IPermissionsChecker.cs, Toggl.Core.UI/Services/PermissionAwareNotificationService.cs, Toggl.Core.UI/Services/PermissionStatus.cs, Toggl.Core.UI/ViewModels/Settings/NotificationSettingsViewModel.cs, Toggl.Droid/Extensions/Reactive/ViewExtensions.cs, Toggl.Droid/Fragments/CalendarFragment.cs, Toggl.Droid/Fragments/MainFragment.ViewBinds.cs, Toggl.Droid/Fragments/MainFragment.cs, Toggl.Droid/Resources/layout/MainFragment.axml, Toggl.Droid/Resources/values-night/Colors.xml, Toggl.Droid/Resources/values/Colors.xml, Toggl.Droid/Services/PermissionsCheckerAndroid.cs, Toggl.Droid/Toggl.Droid.csproj, Toggl.Droid/Views/AnimatedFloatingActionButton.cs, Toggl.iOS.TimerWidgetExtension/TodayViewController.cs, Toggl.iOS/Cells/MainLog/TimeEntriesLogViewCell.cs, Toggl.iOS/Cells/MainLog/TimeEntriesLogViewCell.xib, Toggl.iOS/Helper/PermissionsHelper.cs, Toggl.iOS/Services/PermissionsCheckerIos.cs, Toggl.iOS/ViewControllers/Settings/NotificationSettingsViewController.cs, Toggl.iOS/ViewControllers/Settings/NotificationSettingsViewController.xib
The usual mergeback.
📊 Reports Rewrite project
`git`
Should be none.
No conflicts.
Me. Merge, not _squid_.
=> Reports Rewrite - Mergeback

Toggl.Droid/Extensions/ContextExtensions.cs, Toggl.Droid/Fragments/Calendar/CalendarDayViewPageFragment.cs, Toggl.Droid/Helper/PersistentNotificationsHelper.cs, Toggl.Droid/Properties/AndroidManifest.xml, Toggl.Droid/Views/Calendar/CalendarDayView.Events.cs, Toggl.Droid/Widgets/SuggestionsWidgetListFormFactor.cs, Toggl.Droid/Widgets/SuggestionsWidgetNotLoggedInFormFactor.cs, Toggl.Droid/Widgets/TimeEntryWidgetDefaultFormFactor.cs, build.cake
- Improved sync
- Fixed calendar smart alerts scheduling
- Various other fixes and improvements
https://github.com/toggl/mobileapp/compare/android-2.9-2...android-2.10
Release checklist: #6964 
Testing checklist: #6967
=> Android 2.10 - Kuzumochi

Toggl.Droid/Activities/CalendarSettingsActivity.ViewBinds.cs, Toggl.Droid/Activities/MainTabBarActivity.cs, Toggl.Droid/Activities/StartTimeEntryActivity.cs, Toggl.Droid/Extensions/ActivityExtensions.cs, Toggl.Droid/Presentation/ViewModelCache.cs, Toggl.Droid/Properties/AndroidManifest.xml, Toggl.Droid/Resources/layout/TokenResetActivity.axml, Toggl.Shared.Tests/DateFormatTests.cs, Toggl.Shared/DateFormat.cs
This is the android 2.12 release branch.
- Fixed the settings label for the stopped timer notification configuration
- Fixed a glitch when starting time entries from the calendar view
- Other fixes, performance and sync improvements
https://github.com/toggl/mobileapp/compare/android-2.11.1-2...release/android-2.12-1
I'll merge it when it's time.
=> Android 2.12 - Manju

Toggl.Core.Tests/UI/ViewModels/OnboardingViewModelTests.cs, Toggl.Core.Tests/UI/ViewModels/SignUpViewModelTests.cs, Toggl.Core.UI/ViewModels/OnboardingViewModel.cs, Toggl.Core.UI/ViewModels/SignUpViewModel.cs, Toggl.iOS/Presentation/NavigationPresenter.cs, Toggl.iOS/ViewControllers/LoginViewController.cs, Toggl.iOS/ViewControllers/SignUpViewController.cs, Toggl.iOS/ViewControllers/SignUpViewController.designer.cs, Toggl.iOS/ViewControllers/SignUpViewController.xib, Toggl.iOS/ViewControllers/SignupViewController.designer.cs, Toggl.iOS/ViewControllers/SignupViewController.xib
This applies fixes from the iOS release branch.
Closes #
To have these fixes here.
cherry-pick
Anyone
=> Cherry pick iOS fixes

Toggl.Droid/Properties/AndroidManifest.xml
This is the android 2.14 release branch.
- Added Brazilian Portuguese translations
- Added French translations 
- Fixed a couple of minor crashes across the app
- Improved text contrast on the calendar page
- Other under the hood fixes and improvements
https://github.com/toggl/mobileapp/compare/android-2.13.1...android-2.14
Only myself when the time is ripe
=> Android 2.14 - Ovo de Páscoa

Toggl.Core.UI/ViewModels/OnboardingViewModel.cs, Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist
• We now support Sign in with Apple!
• Added Brazilian Portuguese translations
• Added French translations
• Fixed the Siri shortcut for custom reports
• Fixed a couple of minor crashes across the app
• Other under the hood fixes and improvements
https://github.com/toggl/mobileapp/compare/ios-2.13-5...ios-2.14-2
Only me when ripe and juicy
=> 🍊 iOS 2.14 — Orange

Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist
• We now support Sign in with Apple!
• Added Brazilian Portuguese translations
• Added French translations
• Fixed the Siri shortcut for custom reports
• Fixed a bug on iOS 13.4 where some buttons would become unresponsive
• Fixed a couple of minor crashes across the app
• Other under the hood fixes and improvements
https://github.com/toggl/mobileapp/compare/ios-2.14-2...ios-2.14.1
Only me and only after #7291 is merged
=> 🍊 iOS 2.14.1 — Orange Hotfix #1

Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist, Toggl.iOS/Views/Onboarding/PeriscopeView.cs, Toggl.iOS/Views/Onboarding/VideoView.cs
This fixes minor crashes in the onboarding flow.
• We now support Sign in with Apple!
• Added Brazilian Portuguese translations
• Added French translations
• Fixed the Siri shortcut for custom reports
• Fixed a bug on iOS 13.4 where some buttons would become unresponsive
• Fixed a couple of minor crashes across the app
• Other under the hood fixes and improvements
https://github.com/toggl/mobileapp/compare/ios-2.14.1...ios-2.14.2
Only me and only after both #7291 and #7303 are merged
=> 🍊 iOS 2.14.2 — Orange Hotfix #2

Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist
• Added tighter account security
• Other under the hood fixes and improvements
https://github.com/toggl/mobileapp/compare/ios-2.14.2...ios-2.15
Only me when ripe and juicy
=> 🍐 iOS 2.15 — Pear

Toggl.Droid/Properties/AndroidManifest.xml
- Added tighter account security
- Fixed dark mode support
- Fixed widget UI issues
- Improved sync speed
- Other under the hood fixes and improvements
https://github.com/toggl/mobileapp/compare/android-2.14...android-2.15
Me
=> 🥮 Android 2.15 - Placek

Toggl.Core.Tests/Mocks/MockTimeEntry.cs, Toggl.Core/DataSources/TimeEntriesDataSource.cs, Toggl.Core/Models/FoundationConstructors.cs, Toggl.Core/Models/FoundationModels.Backups.cs, Toggl.Networking.Tests/Sync/Push/PushActionsTests.cs, Toggl.Networking/Models/TimeEntry.Backup.cs, Toggl.Networking/Sync/Push/Serialization/PartiallySerializableTimeEntry.cs, Toggl.Shared/Models/ITimeEntry.Backup.cs, Toggl.Storage.Realm/Models/RealmConstructors.cs, Toggl.Storage.Realm/Models/RealmTimeEntry.Backup.cs, Toggl.Storage.Realm/Models/RealmTimeEntry.cs, Toggl.iOS.Shared/Models/TimeEntry.cs
A bugfix.
Closes #7562 
It wasn't possible to move a TE to a different workspace.
©️ & 🍝 
There shouldn't be any.
Test this in the simulator/emulator!
@kornelijepetak
=> 🐛 Workspace ID backup

Toggl.Core.Tests/Interactors/UserAccess/LogoutInteractorTests.cs, Toggl.Core.UI/ViewModels/EditTimeEntryViewModel.cs, Toggl.Core.UI/ViewModels/MainViewModel.cs, Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs, Toggl.Core/Analytics/BaseAnalyticsService.cs, Toggl.Core/Analytics/IAnalyticsService.cs, Toggl.Core/Interactors/InteractorFactory.UserAccess.cs, Toggl.Core/Interactors/TimeEntry/CreateTimeEntryInteractor.cs, Toggl.Core/Interactors/UserAccess/LogoutInteractor.cs, Toggl.Droid/Fragments/MainFragment.cs, Toggl.Shared/Resources.resx, Toggl.Storage/OnboardingCondition.cs, Toggl.Storage/Settings/IOnboardingStorage.cs, Toggl.Storage/Settings/SettingsStorage.cs, Toggl.iOS/ViewControllers/MainViewController.cs
This cherry-picks the commits already present on the iOS release branch.
Anyone
=> 🍒 Apply iOS release branch changes

Toggl.Core.UI/ViewModels/MainViewModel.cs, Toggl.Droid/Properties/AndroidManifest.xml
A quick hotfix for 2.16. Should fix https://appcenter.ms/orgs/Toggl/apps/Toggl-Android/crashes/errors/455074172u/overview
Changelog is still the same
```
Added Single Sign On support
Improved user onboarding
Improved project color rendering in dark mode
Various bug fixes and improvements
```
Me
=> Android 2.16 hotfix #1

Toggl.Shared/Resources.fr.resx, Toggl.Shared/Resources.ja.resx, Toggl.Shared/Resources.pt.resx, Toggl.Storage.Realm/Sync/ThreeWayMerge.cs, Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist
This is an iOS app 2.17 release PR.
Changelog:
```
- Added support for single sign-on (SSO)
- Improved onboarding for new users
- Improved syncing
```
Diff: https://github.com/toggl/mobileapp/compare/ios-2.16..ios-2.17
🚫
=> iOS 2.17 Raspberry

Toggl.Shared/Resources.fr.resx, Toggl.Shared/Resources.ja.resx, Toggl.Shared/Resources.pt.resx, Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist
A hotfix for the current release.
Ref #7645, ref #7656 
We want to fix an occasional crash in Japanese, French, and Portugese localizations.
🚫
=> iOS hotfix 2.17.1 Raspberry

Toggl.Core/Interactors/Sync/PullDataInteractor.cs, Toggl.Storage.Realm/Queries/ProcessPullResultQuery.cs, Toggl.Storage.Realm/Queries/RealmQueryFactory.cs, Toggl.Storage.Realm/Queries/ResetLocalStateQuery.cs, Toggl.Storage.Realm/Queries/WritePulledData.cs, Toggl.Storage/Queries/IQueryFactory.cs, Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist
This is a hotfix for the 2.17 iOS release. The issue that's being fixed is #7669.
Changelog:
```
- Fixed an issue with syncing
```
We want the app to sync correctly even for users who haven't used the app for a while.
No need to change localization in this release.
🚫
=> Hotfix iOS 2.17.2

Toggl.Droid/Properties/AndroidManifest.xml
This is the Android 2.19 release PR.
Changelog:
```
Changed appearance for Toggl Track rebrand.
Added the start button and running time entry card to the calendar view.
Added more information to items in the calendar view.
Added support for navigating to more dates in the calendar view.
Changed the tabs order.
```
Diff: https://github.com/toggl/mobileapp/compare/android-2.18..android-2.19
🚫
=> Android 2.19 - Tiramisu

Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist, Toggl.iOS/ViewControllers/Calendar/CalendarViewController.cs, Toggl.iOS/ViewControllers/Calendar/CalendarViewController.designer.cs, Toggl.iOS/ViewControllers/Calendar/CalendarViewController.xib, Toggl.iOS/ViewControllers/MainViewController.cs, Toggl.iOS/ViewControllers/MainViewController.designer.cs, Toggl.iOS/ViewControllers/MainViewController.xib
The release of iOS 2.19.3 - Tomato, with a bug fix for the start button.
```
Changed appearance for Toggl Track rebrand.
Added the start button and running time entry card to the calendar view.
Added more information to items in the calendar view.
Added support for navigating to more dates in the calendar view.
Changed the tabs order.
```
NO!
=> iOS 2.19.3 - Tomato hot fix

Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist, Toggl.iOS/ViewControllers/Calendar/CalendarViewController.cs, Toggl.iOS/ViewControllers/Calendar/CalendarViewController.designer.cs, Toggl.iOS/ViewControllers/Calendar/CalendarViewController.xib, Toggl.iOS/ViewControllers/MainViewController.cs, Toggl.iOS/ViewControllers/MainViewController.designer.cs, Toggl.iOS/ViewControllers/MainViewController.xib
A merge from from develop into the project branch. Didn't have any conflicts during the merge.
Merge, don't squash.
=> Merge develop into project/calendar-integration

Toggl.Droid/Properties/AndroidManifest.xml
=> Merge develop into project/onboarding-3.0

Toggl.Core.UI/ViewModels/Calendar/CalendarViewModel.cs, Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Cells/SelectDefaultWorkspaceTableViewCell.xib, Toggl.iOS/Helper/Handoff.cs, Toggl.iOS/Info.plist, Toggl.iOS/ViewControllers/Calendar/CalendarDayViewController.cs, Toggl.iOS/ViewControllers/Calendar/CalendarViewController.cs, Toggl.iOS/ViewControllers/ForgotPasswordViewController.xib, Toggl.iOS/ViewControllers/MainViewController.cs, Toggl.iOS/ViewControllers/SelectDefaultWorkspaceViewController.cs, Toggl.iOS/ViewControllers/TokenResetViewController.xib
Release PR.
```
- Added user Onboarding for the Reports view
- Fixed blurry launch screen
- Updated app icon
- Various bug fixes and improvements
```
Ref #7802
🚫 Not yet
=> iOS 2.20 - Ugni

Toggl.Droid/Activities/MainTabBarActivity.cs, Toggl.Droid/Fragments/MainFragment.cs, Toggl.Droid/Properties/AndroidManifest.xml
A new release, containing a bug fix.
🚫 Not yet
=> Android 2.20.1 - Uštipci Hotfix #1

Toggl.Core.UI/ViewModels/Calendar/CalendarDayViewModel.cs, Toggl.Core.UI/ViewModels/Calendar/ContextualMenu/CalendarContextualMenuViewModel.cs, Toggl.Shared/Resources.resx, Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist, Toggl.iOS/ViewControllers/EditDurationViewController.cs, Toggl.iOS/ViewControllers/EditTimeEntryViewController.cs, Toggl.iOS/ViewControllers/EditTimeEntryViewController.xib, Toggl.iOS/ViewControllers/SelectDateTimeViewController.cs
A release PR.
```
Improved user onboarding in the Calendar View
```
https://github.com/toggl/mobileapp/compare/ios-2.20-2...ios-2.21
Not yet.
=> iOS 2.21 - Vanilla

Toggl.Core.Tests/UI/ViewModels/CalendarContextualMenuViewModelTests.cs, Toggl.Core.UI/ViewModels/Calendar/ContextualMenu/CalendarContextualMenuViewModel.cs, Toggl.Shared/Resources.fr.resx, Toggl.Shared/Resources.ja.resx, Toggl.Shared/Resources.pt.resx, Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist, Toggl.iOS/ViewControllers/Calendar/CalendarDayViewController.cs, Toggl.iOS/ViewSources/CalendarCollectionViewSource.cs, Toggl.iOS/Views/Calendar/CalendarCollectionViewCreateFromSpanHelper.cs
A release PR
```
Improved user onboarding in the Calendar View
Fixed a crash and several other issues in the Calendar View
```
https://github.com/toggl/mobileapp/compare/ios-2.21-1...ios-2.21.1
🚫 Not yet
=> iOS 2.21.1 hotfix

Toggl.Core.Tests/UI/ViewModels/CalendarContextualMenuViewModelTests.cs, Toggl.Core.Tests/UI/ViewModels/CalendarViewModelTests.cs, Toggl.Core.Tests/UI/ViewModels/MainViewModelTests.cs, Toggl.Core.Tests/UI/ViewModels/StartTimeEntryViewModelTests.cs, Toggl.Core.UI/ViewModels/Calendar/CalendarViewModel.cs, Toggl.Core.UI/ViewModels/Calendar/ContextualMenu/CalendarContextualMenuViewModel.cs, Toggl.Core.UI/ViewModels/MainViewModel.cs, Toggl.Core.UI/ViewModels/StartTimeEntryViewModel.cs, Toggl.Droid/Startup/SplashScreen.DeepLink.cs, Toggl.iOS.SiriExtension.UI/Info.plist, Toggl.iOS.SiriExtension/Info.plist, Toggl.iOS.TimerWidgetExtension/Info.plist, Toggl.iOS/Info.plist, Toggl.iOS/Startup/AppDelegate.Deeplink.cs, Toggl.iOS/Startup/AppDelegate.Siri.cs, Toggl.iOS/ViewControllers/StartTimeEntryViewController.cs, Toggl.iOS/Views/Calendar/CalendarCollectionViewCreateFromSpanHelper.cs
=> iOS 2.21.2 Vanilla Hotfix #2
